### ISSUE TITLE
TypeError: Object # has no method ‘flush

### ISSUE THREAD

**Issue by dlplenin** [elrasguno/node-tictactoe#1]
Hi, ur help...

This is the stack of mi CMD:

C:\node\tictactoe>node ttt-server.js
WS: 685647680 draft75 connection

C:\node\tictactoe\node-websocket-server\lib\ws\connection.js:51
      process.stdout.flush();
                     ^
TypeError: Object #<WriteStream> has no method 'flush'
    at Connection.debug (C:\node\tictactoe\node-websocket-server\lib\ws\connecti
on.js:51:22)
    at new Connection (C:\node\tictactoe\node-websocket-server\lib\ws\connection
.js:102:5)
    at Server.<anonymous> (C:\node\tictactoe\node-websocket-server\lib\ws\server
.js:72:7)
    at Server.EventEmitter.emit (events.js:106:17)
    at Socket.socket.ondata (http.js:1924:14)
    at TCP.onread (net.js:495:27)

C:\node\tictactoe>

The ttt-server.js is listening untill the ttt-client.html is open, at this point it crash

Thanks

PD: WIN8 x64

**Comment by lari** [comment]
I have the same issue running node.js v0.10.4 on Mac. Any solutions yet?
